version: "3"
services:
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./data:/data
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["graph-data-science"]
    # - NEO4J_dbms_memory_pagecache_size=4G
    # - NEO4J_dbms_memory_heap_maxSize=4G
    # - NEO4J_dbms_memory_heap_initial__size=4G
    # - NEO4J_dbms_unmanagedExtensionClasses=browser=/browser
    # - NEO4J_browser_remote__content__access__enable=true
