version: "3"
networks:
  mynetwork:
services:
  nginx:
    networks:
      - mynetwork
    build:
      context: ./nginx/
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    depends_on:
      - websocket
  websocket:
    networks:
      - mynetwork
    restart: always
    build:
      context: .
      dockerfile: ./server/Dockerfile
    # ports:
    #   - "4000:4000"
    environment:
      # - REDIS_USER=redis
      # - REDIS_PASSWORD=redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - FIREBASE_CONFIG={"projectId":"react-video-call-thing72","storageBucket":"react-video-call-thing72.appspot.com","locationId":"us-central"}
    depends_on:
      - redis
      - rabbitmq
  matcher:
    networks:
      - mynetwork
    restart: always
    build:
      context: .
      dockerfile: ./matcher/Dockerfile
    # ports:
    #   - "4000:4000"
    environment:
      # - REDIS_USER=redis
      # - REDIS_PASSWORD=redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - FIREBASE_CONFIG={"projectId":"react-video-call-thing72","storageBucket":"react-video-call-thing72.appspot.com","locationId":"us-central"}
    depends_on:
      - redis
      - rabbitmq
  redis:
    networks:
      - mynetwork
    image: redis:latest
    # environment:
    # - REDIS_PASSWORD=redis
    ports:
      - "6379:6379"
  rabbitmq:
    networks:
      - mynetwork
    image: rabbitmq:3-management
    command: rabbitmq-server
    # environment:
    # - REDIS_PASSWORD=redis
    # ports:
    #   - "6379:6379"

  zookeeper:
    image: wurstmeister/zookeeper:latest
    # ports:
    #   - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.11-1.1.1
    ports:
      - "9092:9092"
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_CREATE_TOPICS: "topic-test:1:1"
