packages:
  - 'common'
  - 'data-test'
  - 'common-messaging'
  - 'data-service'
  - 'neo4j-jobs'
  - 'socketio-service'
  - 'matchmaker-event'
  - 'socketio-event'
  - 'options-service'
  - 'puppeteer'
