dependencies:
  firebase_auth: ^4.2.9
  flutter:
    sdk: flutter
  flutter_webrtc: ^0.9.19
  geolocator: ^9.0.2
  get: ^4.6.5
  get_storage: ^2.1.1
  google_maps: ^6.2.0
  google_maps_flutter: ^2.2.5
  http: ^0.13.5
  # loading_animation_widget: ^1.2.0+4
  package_info_plus: ^3.1.0
  socket_io_client: ^2.0.1
  uuid: ^3.0.7
description: A new Flutter project.
dev_dependencies:
  flutter_native_splash: ^2.0.4
  change_app_package_name: ^1.1.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
environment:
  sdk: '>=2.18.6 <3.0.0'
flutter:
  uses-material-design: true
name: flutter_app
publish_to: none
version: 1.0.145
