dependencies:
  cloud_firestore: ^4.8.2
  file_picker: ^5.3.1
  firebase_analytics: ^10.4.3
  firebase_auth: ^4.2.9
  firebase_core: ^2.13.0
  firebase_crashlytics: ^3.3.3
  firebase_performance: ^0.9.2+3
  firebase_storage: ^11.2.4
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.0.3
  flutter_map: ^4.0.0
  flutter_native_splash: ^2.0.4
  flutter_webrtc: ^0.9.19
  geolocator: ^9.0.2
  get: ^4.6.5
  get_storage: ^2.1.1
  http: ^0.13.5
  latlong2: ^0.8.2
  package_info_plus: ^3.1.0
  socket_io_client: ^2.0.1
description: A new Flutter project.
dev_dependencies:
  change_app_package_name: ^1.1.0
  dependency_validator: ^3.0.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
environment:
  sdk: '>=3.0.0'
flutter:
  uses-material-design: true
name: flutter_app
publish_to: none
version: 1.0.261
