dependencies:
  cloud_firestore: ^4.3.1
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.2.9
  firebase_core: ^2.4.1
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.0.4
  flutter_webrtc: ^0.9.19
  geolocator: ^9.0.2
  http: ^0.13.5
  loading_animation_widget: ^1.2.0+4
  provider: ^6.0.5
  shared_preferences: ^2.0.20
  socket_io_client: ^2.0.1
  statemachine: ^3.3.1
description: A new Flutter project.
dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
environment:
  sdk: '>=2.18.6 <3.0.0'
flutter:
  uses-material-design: true
name: flutter_app
publish_to: none
version: 1.0.73
