dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.0.4
  flutter_webrtc: ^0.9.18
  loading_animation_widget: ^1.2.0+4
  provider: ^6.0.5
  socket_io_client: ^2.0.0
description: A new Flutter project.
dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
environment:
  sdk: ">=2.18.6 <3.0.0"
flutter:
  uses-material-design: true
name: flutter_app
publish_to: none
version: 1.0.1
