apiVersion: v1
kind: Pod
metadata:
  name: omegle-bot
spec:
  containers:
    - name: vpn
      image: andrewdelph/omegle:latest
      imagePullPolicy: Always
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
  #     securityContext:
  #       privileged: true
  #     volumeMounts:
  #       - name: tun-device
  #         mountPath: /dev/net/tun
  # volumes:
  #   - name: tun-device
  #     hostPath:
  #       path: /dev/net/tun
