apiVersion: v1
kind: Namespace
metadata:
  name: bot
---
apiVersion: v1
kind: Pod
metadata:
  name: omegle-bot
  namespace: bot
spec:
  containers:
    - name: vpn
      image: andrew-delph/video-call-puppeteer
      imagePullPolicy: Always
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
      env:
        - name: METRICS
          value: 'TRUE'
