apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: neo4j-claim0
  name: neo4j-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
status: {}
