apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: neo4j
  name: neo4j
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: neo4j
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: neo4j
    spec:
      # initContainers:
      #   - name: init-plugins
      #     image: 'appropriate/curl:latest'
      #     imagePullPolicy: 'IfNotPresent'
      #     volumeMounts:
      #       - name: neo4j-claim0
      #         mountPath: /plugins
      #         subPath: plugins
      #     command:
      #       - '/bin/sh'
      #       - '-c'
      #       - |
      #         curl -L https://graphdatascience.ninja/neo4j-graph-data-science-2.3.1.jar -O
      #         cp -R neo4j-graph-data-science-2.3.1.jar /plugins
      containers:
        - env:
            - name: NEO4J_AUTH
              value: neo4j/password
            # - name: NEO4J_PLUGINS
            #   value: '["graph-data-science"]'
            - name: NEO4J_server_config_strict__validation_enabled
              value: 'false'
          image: neo4j:5.5.0
          imagePullPolicy: 'Always'
          name: neo4j
          ports: ## Ports to map
            - containerPort: 7474
              name: http
            - containerPort: 7687
              name: bolt
            - containerPort: 7473
              name: https
          resources: {}
          volumeMounts:
            - mountPath: /data
              name: neo4j-claim0
              subPath: data
            # - mountPath: /plugins
            #   name: neo4j-claim0
            #   subPath: plugins
      restartPolicy: Always
      serviceAccountName: ''
      volumes:
        - name: neo4j-claim0
          persistentVolumeClaim:
            claimName: neo4j-claim0
status: {}
