adminUser: admin
adminPassword: password

sidecar:
  dashboards:
    enabled: true
    label: grafana_dashboard
    labelValue: '1'
    annotations: {}
    multicluster:
      global:
        enabled: false
      etcd:
        enabled: false
    provider:
      allowUiUpdates: false
  datasources:
    enabled: true
    defaultDatasourceEnabled: true
    isDefaultDatasource: true
    uid: prometheus
    annotations: {}
    createPrometheusReplicasDatasources: false
    label: grafana_datasource
    labelValue: '1'

    exemplarTraceIdDestinations: {}
