test_pod:
  enabled: true
  image: bats/bats:v1.1.0
  pullPolicy: IfNotPresent

grafana:
  enabled: false
  # adminUser: admin
  # adminPassword: password

loki:
  enabled: true
  isDefault: false
  url: http://{{(include "loki.serviceName" .)}}:{{ .Values.loki.service.port }}
  readinessProbe:
    httpGet:
      path: /ready
      port: http-metrics
    initialDelaySeconds: 45
  livenessProbe:
    httpGet:
      path: /ready
      port: http-metrics
    initialDelaySeconds: 45
  datasource:
    jsonData: '{}'
    uid: ''

promtail:
  enabled: true
  config:
    serverPort: 3101
    clients:
      - url: http://{{ .Release.Name }}:3100/loki/api/v1/push
    snippets:
      # addScrapeJobLabel: true
      # extraLimitsConfig: |
      #   readline_rate: 1000
      #   readline_burst: 2000
      #   readline_rate_enabled: true
      extraRelabelConfigs:
        # keep all kubernetes labels
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - source_labels: [serving_knative_dev_service]
          regex: '(.+)'
          target_label: 'app'
      pipelineStages:
        - drop:
            source: 'namespace'
            expression: '(kube-public|kube-system)'
        - drop:
            older_than: 1h
            drop_counter_reason: 'line_too_old'
        - cri:
        - json:
            expressions:
              level: level
        - labels:
            level:
        - output:
            source: msg

# proxy is currently only used by loki test pod
# Note: If http_proxy/https_proxy are set, then no_proxy should include the
# loki service name, so that tests are able to communicate with the loki
# service.
proxy:
  http_proxy: ''
  https_proxy: ''
  no_proxy: ''
