prometheus:
  url: http://loki-prometheus-server.monitoring
  port: 80
rules:
  default: false
  custom:
    - seriesQuery: 'rabbitmq_queue_messages_ready'
      name:
        matches: ''
        as: 'readyQueue'
      resources:
        template: <<.Resource>>
      metricsQuery: avg_over_time( sum(<<.Series>>{queue="readyQueue"}) by (<<.GroupBy>>) [1m:])
    - seriesQuery: 'rabbitmq_queue_messages_ready'
      name:
        matches: ''
        as: 'matchQueue'
      resources:
        template: <<.Resource>>
      metricsQuery: avg_over_time( sum(<<.Series>>{queue=~"matchQueue|matchmakerQueueName"}) [1m:])
