prometheus:
  url: http://loki-prometheus-server.monitoring
  port: 80
rules:
  default: false
  custom:
    - seriesQuery: 'rabbitmq_queue_messages_ready'
      name:
        matches: ''
        as: 'matchmaker-event'
      resources:
        template: <<.Resource>>
      metricsQuery: avg_over_time( sum(<<.Series>>{queue=~"readyQueue|matchmaker-eventQueue"}) by (<<.GroupBy>>) [1m:])
    - seriesQuery: 'rabbitmq_queue_messages_ready'
      name:
        matches: ''
        as: 'socketio-event'
      resources:
        template: <<.Resource>>
      metricsQuery: avg_over_time( sum(<<.Series>>{queue=~"matchQueue"}) by (<<.GroupBy>>) [1m:])
