prometheus:
  url: http://prometheus-operated.monitoring.svc
  port: 9090
rules:
  default: false
  custom:
    - seriesQuery: 'rabbitmq_queue_messages'
      name:
        matches: ''
        as: 'readyQueue'
        template: <<.Resource>>
      metricsQuery: avg_over_time( sum(<<.Series>>{queue="readyQueue"}) by (<<.GroupBy>>) [1m:])

    - seriesQuery: 'rabbitmq_queue_messages'
      name:
        matches: ''
        as: 'matchQueue'
      resources:
        template: <<.Resource>>
      metricsQuery: avg_over_time( sum(<<.Series>>{queue="matchQueue"}) by (<<.GroupBy>>) [1m:])
