rabbitmq:
  url: http://rabbitmq.default.svc.cluster.local:15672
  user: guest
  password: guest
  capabilities: bert,no_sort
  include_queues: '.*'
  include_vhost: '.*'
  skip_queues: '^$'
  skip_verify: 'false'
  skip_vhost: '^$'
  exporters: 'exchange,node,overview,queue'
  output_format: 'TTY'
  timeout: 30
  max_queues: 0
  excludeMetrics: ''

annotations:
  prometheus.io/scrape: 'true'
  prometheus.io/path: /metrics
  prometheus.io/port: '9419'
# prometheus:
#   monitor:
#     enabled: true
#     additionalLabels:
#       release: loki # this has to be the same name as the kube-prometheus-stack name
