apiVersion: v1
kind: Namespace
metadata:
  name: knative-serving
---
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  # ...
  ingress:
    kourier:
      enabled: true
  config:
    features:
      kubernetes.podspec-priorityclassname: 'enabled'
    defaults:
      max-revision-timeout-seconds: '3600'
    network:
      ingress-class: 'kourier.ingress.networking.knative.dev'
      auto-tls: Enabled
      # http-protocol: Redirected
  deployments:
    - name: activator
      resources:
        - container: activator
          requests:
            cpu: 25m
            memory: 100Mi
    - name: net-kourier-controller
      resources:
        - container: controller
          requests:
            cpu: 25m
            memory: 100Mi
    - name: 3scale-kourier-gateway
      resources:
        - container: kourier-gateway
          requests:
            cpu: 25m
            memory: 100Mi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-gc
  namespace: knative-serving
data:
  min-non-active-revisions: '0'
  max-non-active-revisions: '0'
  retain-since-create-time: 'disabled'
  retain-since-last-active-time: 'disabled'
# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: config-defaults
#   namespace: knative-serving
# data:
#   max-revision-timeout-seconds: '3600'
# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: config-features
#   namespace: knative-serving
# data:
#   kubernetes.podspec-priorityclassname: 'enabled'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-autoscaler
  namespace: knative-serving
data:
  enable-scale-to-zero: 'true'
  allow-zero-initial-scale: 'true'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-domain
  namespace: knative-serving
data:
  example.com: ''
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-http01-issuer
spec:
  acme:
    privateKeySecretRef:
      name: letsencrypt-http01-issuer
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - http01:
          ingress:
            class: kourier
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-certmanager
  namespace: knative-serving
  labels:
    networking.knative.dev/certificate-provider: cert-manager
data:
  issuerRef: |
    kind: ClusterIssuer
    name: letsencrypt-http01-issuer
