apiVersion: v1
kind: Namespace
metadata:
  name: knative-serving
---
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  # ...
  ingress:
    kourier:
      enabled: true
  config:
    network:
      ingress-class: 'kourier.ingress.networking.knative.dev'
  deployments:
    - name: activator
      resources:
        - container: activator
          requests:
            cpu: 25m
            memory: 100Mi
    - name: net-kourier-controller
      resources:
        - container: controller
          requests:
            cpu: 25m
            memory: 100Mi
    - name: 3scale-kourier-gateway
      resources:
        - container: kourier-gateway
          requests:
            cpu: 25m
            memory: 100Mi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-gc
  namespace: knative-serving
data:
  min-non-active-revisions: '0'
  max-non-active-revisions: '0'
  retain-since-create-time: 'disabled'
  retain-since-last-active-time: 'disabled'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-autoscaler
  namespace: knative-serving
data:
  enable-scale-to-zero: 'true'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-domain
  namespace: knative-serving
data:
  solarsim.net: ''
# ---
# apiVersion: networking.internal.knative.dev/v1alpha1
# kind: ClusterDomainClaim
# metadata:
#   name: solarsim.net
# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: config-domain
#   namespace: knative-serving
#   labels:
#     app.kubernetes.io/name: knative-serving
#     app.kubernetes.io/component: controller
#     app.kubernetes.io/version: devel
# data:
#   solarsim.net: |
