apiVersion: v1
kind: Pod
metadata:
  name: omegle-bot
  namespace: bot
spec:
  terminationGracePeriodSeconds: 5
  containers:
    - name: runner
      image: ghcr.io/andrew-delph/video-call-puppeteer:latest
      imagePullPolicy: Always
      ports:
        - containerPort: 80
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
      env:
        - name: METRICS
          value: 'TRUE'
      readinessProbe:
        httpGet:
          path: /health
          port: 80
        failureThreshold: 6
        periodSeconds: 10
      livenessProbe:
        httpGet:
          path: /health
          port: 80
        initialDelaySeconds: 60
        periodSeconds: 10
