apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: default
imagePullSecrets:
  - name: docker-secret
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: knative-serving
imagePullSecrets:
  - name: docker-secret
