apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: feedback
  name: feedback
spec:
  ports:
    - name: '8080'
      port: 8080
      targetPort: 8080
  selector:
    app: feedback
status:
  loadBalancer: {}
