apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: feedback
  name: feedback
spec:
  # replicas: 1
  selector:
    matchLabels:
      app: feedback
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: feedback
    spec:
      containers:
        - env:
            - name: FIREBASE_CONFIG
              value: '{"projectId":"react-video-call-thing72","storageBucket":"react-video-call-thing72.appspot.com","locationId":"us-central"}'
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: '6379'
          image: andrewdelph/video-call-feedback:latest
          name: feedback
          ports:
            - containerPort: 3000
          resources:
            # requests:
            #   cpu: '100m'
            #   memory: '100Mi'
            limits:
              cpu: '500m'
              memory: '512Mi'
      restartPolicy: Always
status: {}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-feedback
spec:
  minReplicas: 1
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: feedback
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
