apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: matchmaker
  name: matchmaker
spec:
  ports:
    - name: '4000'
      port: 4000
      targetPort: 4000
  selector:
    app: matchmaker
status:
  loadBalancer: {}
