apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: matchmaker
  name: matchmaker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matchmaker
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: matchmaker
    spec:
      containers:
        - env:
            - name: FIREBASE_CONFIG
              value: '{"projectId":"react-video-call-thing72","storageBucket":"react-video-call-thing72.appspot.com","locationId":"us-central"}'
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: '6379'
          image: andrewdelph/video-call-matchmaker:latest
          name: matchmaker
          ports:
            - containerPort: 4000
          resources:
            # requests:
            #   cpu: '512m'
            #   memory: '250Mi'
            limits:
              cpu: '512m'
              memory: '450Mi'
      restartPolicy: Always
status: {}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-matchmaker
spec:
  minReplicas: 1
  maxReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: matchmaker
  metrics:
    - type: Object
      object:
        metric:
          name: readyQueue
        target:
          type: Value
          value: 100
        describedObject:
          apiVersion: '/v1'
          kind: 'Service'
          name: prometheus-rabbitmq-exporter
    # - type: Resource
    #   resource:
    #     name: cpu
    #     target:
    #       type: Utilization
    #       averageUtilization: 80
    # - type: Resource
    #   resource:
    #     name: memory
    #     target:
    #       type: Utilization
    #       averageUtilization: 80
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: matchmaker
  name: matchmaker
spec:
  ports:
    - name: '4000'
      port: 4000
      targetPort: 4000
  selector:
    app: matchmaker
status:
  loadBalancer: {}
