apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -o ./k8/
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    app: matchmaker
  name: matchmaker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matchmaker
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -o ./k8/
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/react-video-call-default: 'true'
        app: matchmaker
    spec:
      containers:
        - env:
            - name: FIREBASE_CONFIG
              value: '{"projectId":"react-video-call-thing72","storageBucket":"react-video-call-thing72.appspot.com","locationId":"us-central"}'
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: '6379'
          image: andrewdelph/video-call-matchmaker:latest
          name: matchmaker
          ports:
            - containerPort: 4000
          resources:
            # requests:
            #   cpu: '512m'
            #   memory: '250Mi'
            limits:
              cpu: '1000m'
              memory: '500Mi'
      restartPolicy: Always
status: {}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-matchmaker
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: matchmaker
  metrics:
    - type: Object
      object:
        metric:
          name: readyQueue
        target:
          type: Value
          value: 100
        describedObject:
          apiVersion: '/v1'
          kind: 'Service'
          name: prometheus-rabbitmq-exporter
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
