apiVersion: batch/v1
kind: CronJob
metadata:
  name: neo4j-jobs-train
spec:
  concurrencyPolicy: Forbid
  schedule: '0 0 * * *'
  successfulJobsHistoryLimit: 1
  suspend: true
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: neo4j-jobs
              image: ghcr.io/andrew-delph/video-call-neo4j-jobs:latest
              imagePullPolicy: Always
              env:
                - name: JOB
                  value: TRAIN
          restartPolicy: Never
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: neo4j-jobs-compute
spec:
  concurrencyPolicy: Forbid
  schedule: '0 1-23 * * *'
  successfulJobsHistoryLimit: 1
  suspend: true
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: neo4j-jobs
              image: ghcr.io/andrew-delph/video-call-neo4j-jobs:latest
              imagePullPolicy: Always
              env:
                - name: JOB
                  value: COMPUTE
          restartPolicy: Never
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: neo4j-jobs-short-predict
spec:
  concurrencyPolicy: Forbid
  schedule: '* * * * *'
  suspend: false
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 3600 # TTL set to 1 hour (3600 seconds)
      activeDeadlineSeconds: 100
      template:
        spec:
          terminationGracePeriodSeconds: 300
          containers:
            - name: neo4j-jobs
              image: ghcr.io/andrew-delph/video-call-neo4j-jobs:latest
              imagePullPolicy: Always
              env:
                - name: JOB
                  value: SHORT_PREDICT
          restartPolicy: Never
