apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: neo4j-grpc-server
  name: neo4j-grpc-server
spec:
  ports:
    - name: '8080'
      port: 8080
      targetPort: 8080
  selector:
    app: neo4j-grpc-server
status:
  loadBalancer: {}
