apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-extra-conf
data:
  rabbitmq-extra-conf.conf: |
    # Add your RabbitMQ configuration here
    # prometheus.return_per_object_metrics = true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: rabbitmq
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rabbitmq
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: rabbitmq-extra-conf
      priorityClassName: 'high-priority'
      containers:
        - args:
            - rabbitmq-server
          image: heidiks/rabbitmq-delayed-message-exchange:3.10.2-management
          name: rabbitmq
          ports:
            - containerPort: 5672
            - containerPort: 15672
            - containerPort: 15692
          volumeMounts:
            - name: config-volume
              mountPath: /etc/rabbitmq/conf.d/rabbitmq-extra-conf.conf
              subPath: rabbitmq-extra-conf.conf
              readOnly: true
          resources:
            requests:
              cpu: '25m'
              memory: '100Mi'
            limits:
              cpu: '512m'
              memory: '250Mi'
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: rabbitmq
  name: rabbitmq
spec:
  ports:
    - name: '5672'
      port: 5672
      targetPort: 5672
    - name: '15672'
      port: 15672
      targetPort: 15672
    - name: '15692'
      port: 15692
      targetPort: 15692
  selector:
    app: rabbitmq
status:
  loadBalancer: {}
