apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: rabbitmq
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rabbitmq
    spec:
      priorityClassName: 'high-priority'
      containers:
        - args:
            - rabbitmq-server
          image: heidiks/rabbitmq-delayed-message-exchange:3.10.2-management
          name: rabbitmq
          ports:
            - containerPort: 5672
            - containerPort: 15672
          resources:
            requests:
              cpu: '25m'
              memory: '100Mi'
            limits:
              cpu: '512m'
              memory: '250Mi'
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: rabbitmq
  name: rabbitmq
spec:
  ports:
    - name: '5672'
      port: 5672
      targetPort: 5672
    - name: '15672'
      port: 15672
      targetPort: 15672
  selector:
    app: rabbitmq
status:
  loadBalancer: {}
