apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: redis-commander
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: '1'
        autoscaling.knative.dev/max-scale: '1'
        autoscaling.knative.dev/initial-scale: '1'
        autoscaling.knative.dev/class: 'kpa.autoscaling.knative.dev'
    spec:
      containers:
        - image: rediscommander/redis-commander:latest
          env:
            - name: REDIS_HOSTS
              value: redis
          ports:
            - containerPort: 8081
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: redis-commander-lb
spec:
  type: LoadBalancer
  selector:
    serving.knative.dev/service: redis-commander
  ports:
    - name: http
      port: 8081
      targetPort: 8081
