apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: redis
    spec:
      nodeSelector:
        cloud.google.com/gke-spot: 'true'
      containers:
        - image: redis:latest
          name: redis
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: '25m'
              memory: '250Mi'
            limits:
              memory: '250Mi'
              cpu: '512m'
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: redis
  name: redis
spec:
  ports:
    - name: '6379'
      port: 6379
      targetPort: 6379
  selector:
    app: redis
status:
  loadBalancer: {}
