apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: websocket
  name: websocket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: websocket
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: websocket
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: secrets
          image: andrewdelph/video-call-websocket:latest
          name: websocket
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: '25m'
              memory: '250Mi'
            limits:
              cpu: '512m'
              memory: '250Mi'
      restartPolicy: Always
status: {}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-websocket
spec:
  minReplicas: 1
  maxReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: websocket
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 60
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: websocket
  name: websocket
spec:
  ports:
    - name: '80'
      port: 80
      targetPort: 80
  selector:
    app: websocket
status:
  loadBalancer: {}
