apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: websocket
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: '1'
        autoscaling.knative.dev/max-scale: '1'
        autoscaling.knative.dev/initial-scale: '1'
        autoscaling.knative.dev/class: 'kpa.autoscaling.knative.dev'
    spec:
      nodeSelector:
        cloud.google.com/gke-spot: 'true'
      timeoutSeconds: 3600
      containers:
        - image: andrewdelph/video-call-websocket:latest
          envFrom:
            - configMapRef:
                name: secrets
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: '25m'
              memory: '250Mi'
            limits:
              cpu: '250m'
              memory: '250Mi'
---
apiVersion: networking.internal.knative.dev/v1alpha1
kind: ClusterDomainClaim
metadata:
  name: ws.solarsim.net
spec:
  namespace: default
---
apiVersion: serving.knative.dev/v1alpha1
kind: DomainMapping
metadata:
  name: ws.solarsim.net
  namespace: default
  # annotations:
  #   kourier.knative.dev/disable-http2: 'true' # kubectl annotate domainmapping ws.solarsim.net kourier.knative.dev/disable-http2=true
spec:
  ref:
    name: websocket
    kind: Service
    apiVersion: serving.knative.dev/v1
