apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: websocket
  name: websocket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: websocket
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: websocket
    spec:
      containers:
        - env:
            - name: FIREBASE_CONFIG
              value: '{"projectId":"react-video-call-thing72","storageBucket":"react-video-call-thing72.appspot.com","locationId":"us-central"}'
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: '6379'
          image: andrewdelph/video-call-websocket:latest
          name: websocket
          ports:
            - containerPort: 4000
          resources:
            # requests:
            #   cpu: '512m'
            #   memory: '250Mi'
            limits:
              cpu: '512m'
              memory: '500Mi'
      restartPolicy: Always
status: {}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-websocket
spec:
  minReplicas: 1
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: websocket
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 50
