apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: websocket
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: '1'
        autoscaling.knative.dev/max-scale: '3'
        autoscaling.knative.dev/initial-scale: '1'
        autoscaling.knative.dev/class: 'kpa.autoscaling.knative.dev'
    spec:
      timeoutSeconds: 3600
      priorityClassName: 'mid-priority'
      containers:
        - image: andrewdelph/video-call-websocket:latest
          envFrom:
            - configMapRef:
                name: secrets
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: networking.internal.knative.dev/v1alpha1
kind: ClusterDomainClaim
metadata:
  name: ws.andrewdelph.com
spec:
  namespace: default
---
apiVersion: serving.knative.dev/v1alpha1
kind: DomainMapping
metadata:
  name: ws.andrewdelph.com
  namespace: default
  # annotations:
  #   kourier.knative.dev/disable-http2: 'true' # kubectl annotate domainmapping ws.andrewdelph.com kourier.knative.dev/disable-http2=true
spec:
  ref:
    name: websocket
    kind: Service
    apiVersion: serving.knative.dev/v1
