apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: websocket
  name: websocket
spec:
  ports:
    - name: '4000'
      port: 4000
      targetPort: 4000
  selector:
    app: websocket
status:
  loadBalancer: {}
