name: Deploy updates to k8
concurrency:
  group: deploy_k8
  cancel-in-progress: true
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - 'flutter_app/**'
env:
  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install CLI tools from OpenShift Mirror (knative)
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          kn: '1.7.1'

      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: deploy default services
        run: |
          cd k8
          make apply

      - name: deploy monitoring services
        run: |
          cd monitoring
          make apply

      - name: Mount bazel cache
        uses: actions/cache@v3
        with:
          path: '/home/runner/.cache/bazel'
          key: bazel

      - name: Run deploy.sh
        run: ./deploy.sh
