name: Deploy updates to k8
'on':
  push:
    branches:
      - master
    paths-ignore:
      - 'flutter_app/**'
env:
  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install CLI tools from OpenShift Mirror (knative)
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          kn: 'latest'
      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: make apply
        run: |
          cd k8
          make apply
      - name: Run deploy.sh
        run: ./deploy.sh
