name: Deploy Firebase Functions
on:
  push:
    branches:
      - master
    paths:
      - "functions/**"
      - "firebase.json"
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.5.0-chrome94-ff93
      options: --user 1001 # ← THIS IS THE IMPORTANT LINE!
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: set config
        uses: w9jds/firebase-action@master
        with:
          args: functions:config:set redis.user="${{ secrets.REDIS_USER }}" redis.pass="${{ secrets.REDIS_PASS }}"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Deploy to Firebase Functions
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
