name: Deploy updates to k8
on:
  push:
    # branches:
    #   - master
env:
  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-hub/kubectl@master
        with:
          args: config get-contexts
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        run: |
          echo before
          echo $KUBECONFIG
          echo $KUBE_CONFIG
          kubectl get pods --kubeconfig=$KUBE_CONFIG
          echo after
          kubectl config get-contexts
          kubectl cluster-info dump
          cd k8
          make apply
      - name: Run deploy.sh
        run: ./deploy.sh
