name: Deploy server to gcloud run
"on":
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: "actions/checkout@v3"

      - uses: "google-github-actions/auth@v1"
        with:
          workload_identity_provider: "projects/619217777312/locations/global/workloadIdentityPools/wi-pool/providers/wi-pool"
          service_account: "react-video-call-GA@react-video-call-thing72.iam.gserviceaccount.com"

      - id: "deploy"
        uses: "google-github-actions/deploy-cloudrun@v1"
        with:
          service: "react-video-call"
          source: "."

      - name: "Use output"
        run: 'curl "${{ steps.deploy.outputs.url }}"'
